### ISSUE TITLE
Connect to local Model

### ISSUE THREAD

**Issue by sstasik645** [huggingface/llm-intellij#1]
Hi, 

Will I be able to connect to my local Model?
Did you release the plugin to the marketplace? I can't find it.

Thanks,
Stasik

**Comment by McPatate** [comment]
Hello, yes you will, provided the model is behind an API supported by the plugin.

I've released the extension to the marketplace, I am still waiting for JetBrains' approval.

**Comment by McPatate** [comment]
FYI it's available on the marketplace :)
